language: node_js
dist: trusty
node_js:
  - 6.10

addons:
  firefox: "55.0"

notifications:
  email: false

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - geckodriver &

script:
  - npm run ci
